# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0927ffe0a1f59d3d7790280bc736d8421f69185e4c25dc2429c7b25e46f7c7a77db2bae7e5c8e4491fb89762945c2692a03ed72882411cc298b5dd4c840444e0

test:
  secret_key_base: f108eaf43fa838de88271fd404cd9c427967b840f6f432dba792c492b234f839aadb9d14026615ef81658cb171321367a79a0abfff458ce7ac9affef6e76e301

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
